apiVersion: v1
kind: Pod
metadata:
  name: busybox-config
  namespace: pgs-upskill
  labels:
    project: busybox-config
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sleep"]
      args: ["10000"]
      volumeMounts:
        - mountPath: "/var/config/my-config"
          name: config-file
          readOnly: true
  volumes:
    - name: config-file
      configMap:
        name: my-config

