apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: pgs-upskill
  labels:
    project: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/echo"]
      args: ["Hello $(NAME)"]
      env:
        - name: NAME
          value: "World"