apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-geo-db-write-service
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-geo-db
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: {{ $.Release.Name }}-geo-db
