apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret
  namespace: pgs-upskill
  labels:
    project: busybox-secret
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/echo"]
      args: ["$(SECRET_MESSAGE)"]
      env:
        - name: SECRET_MESSAGE
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: message
