apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-deployment
  namespace: pgs-upskill
  labels:
    app: geo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geo
  template:
    metadata:
      name: geo-
      namespace: pgs-upskill
      labels:
        app: geo
    spec:
      containers:
        - name: app
          image: geo-service:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: KU_GEO_DB_HOST_READ
              value: "geo-mysql-service-read.pgs-upskill.svc.cluster.local"
            - name: KU_GEO_DB_HOST_WRITE
              value: "geo-mysql-0.geo-mysql-service.pgs-upskill.svc.cluster.local"
            - name: KU_GEO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: geo-mysql-secret
                  key: name
            - name: KU_GEO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: geo-mysql-secret
                  key: username
            - name: KU_GEO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geo-mysql-secret
                  key: password