apiVersion: v1
kind: Service
metadata:
  name: geo-service
  namespace: pgs-upskill
  labels:
    app: geo
spec:
  selector:
    app: geo
  ports:
    - port: 80
      targetPort: 8000
      name: app
  type: NodePort