apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-museum-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-museum
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage_size }}