apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-museum-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-museum
spec:
  ports:
    - port: {{ .Values.port }}
      name: museum
      targetPort: {{ .Values.port }}
  type: NodePort
  selector:
    app: {{ .Release.Name }}-museum
