apiVersion: v1
kind: Pod
metadata:
  name: test-mysql
  labels:
    app: test-mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
---
apiVersion: v1
kind: Service
metadata:
  name: test-mysql-service
  labels:
    app: test-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: test-mysql