apiVersion: v1
kind: Service
metadata:
  name: geo-mysql-service
  namespace: pgs-upskill
  labels:
    app: geo-mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: geo-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: geo-mysql-service-read
  namespace: pgs-upskill
  labels:
    app: geo-mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: geo-mysql