apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: pgs-upskill
  name: geo-mysql-pv-1
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql/1/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: pgs-upskill
  name: geo-mysql-pv-2
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql/2/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: pgs-upskill
  name: geo-mysql-pv-3
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql/3/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: pgs-upskill
  name: geo-mysql-pv-4
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql/4/
    type: DirectoryOrCreate