apiVersion: v1
kind: Pod
metadata:
  namespace: pgs-upskill
  name: nginx-any
  labels:
    project: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.17.4
      ports:
        - containerPort: 80