apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
  namespace: pgs-upskill
  labels:
    app: time
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      name: time-
      namespace: pgs-upskill
      labels:
        app: time
    spec:
      containers:
        - name: app
          image: time-service:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          env:
            - name: KU_TIME_GEO_SERVICE_URL
              value: "http://geo-service.pgs-upskill.svc.cluster.local"