apiVersion: v1
kind: Service
metadata:
  name: time-service
  namespace: pgs-upskill
  labels:
    app: time
spec:
  selector:
    app: time
  ports:
    - port: 80
      targetPort: 7000
      name: app
  type: NodePort